"""
Review Summarizer Node
"""
import json
from datetime import datetime

from loguru import logger

from app.reviewer.state import ReviewState
from app.reviewer.prompts import create_summary_prompt
from app.reviewer.llm import get_llm
from app.reviewer.utils import parse_llm_json_response


async def summarize_review(state: ReviewState) -> dict:
    """모든 리뷰를 종합하여 최종 코멘트를 생성하는 노드.

    Args:
        state: 현재 리뷰 상태.

    Returns:
        ``final_review``, ``review_decision``, ``needs_retry``, ``messages``가 포함된 상태 업데이트 딕셔너리.
    """
    logger.info("📝 최종 리뷰 요약 시작...")

    pr_data = state["pr_data"]
    pr_intent = state.get("pr_intent", {})
    risk_assessment = state.get("risk_assessment", {})
    file_reviews = state.get("file_reviews", [])
    repo_skills = state.get("repo_skills", [])
    previous_review = state.get("previous_review")

    logger.info(f"총 {len(file_reviews)}개 파일 리뷰 결과를 종합 중...")

    try:
        # LLM 초기화 (Provider에 따라 자동 선택)
        llm = get_llm(temperature=0.1)  # 약간의 창의성 허용

        # 프롬프트 생성
        prompt = create_summary_prompt(
            pr_data, pr_intent, risk_assessment, file_reviews, repo_skills, previous_review
        )

        # LLM 호출
        response = await llm.ainvoke(prompt)
        response_text = response.content

        logger.debug(f"Summary 응답: {response_text[:200]}...")

        # JSON 파싱
        try:
            summary = parse_llm_json_response(response_text)

            decision = summary.get("decision", "COMMENT")
            final_comment = summary.get("comment", response_text)

            # 재시도 판단: 에러 파일이 있거나 LLM이 재리뷰 필요하다고 판단한 경우
            error_files = [r for r in file_reviews if r.get("status") == "ERROR"]
            llm_needs_retry = summary.get("needs_deeper_review", False)
            needs_retry = bool(error_files) or llm_needs_retry

            if needs_retry:
                reason = f"에러 파일 {len(error_files)}개" if error_files else "LLM 판단"
                logger.info(f"🔄 재리뷰 필요 판단: {reason}")
            logger.info(f"✅ 최종 리뷰 완료: {decision}")
            logger.debug(f"리뷰 코멘트 길이: {len(final_comment)} 자")

        except json.JSONDecodeError as e:
            logger.error(f"JSON 파싱 실패, 원본 텍스트 사용: {e}")
            decision = "COMMENT"
            final_comment = response_text
            needs_retry = False

        return {
            "final_review": final_comment,
            "review_decision": decision,
            "needs_retry": needs_retry,
            "messages": [{
                "role": "summarizer",
                "content": response_text,
                "timestamp": datetime.now().isoformat()
            }]
        }

    except Exception as e:
        logger.error(f"❌ 리뷰 요약 중 오류 발생: {e}")

        # 폴백: 간단한 요약 생성
        fallback_comment = f"""## 🤖 AI 코드 리뷰

### ⚠️ 리뷰 생성 중 오류 발생

리뷰를 완전히 생성하지 못했습니다: {str(e)}

### 📊 기본 정보
- PR: {pr_data.title}
- 파일: {pr_data.changed_files_count}개
- 변경: +{pr_data.total_additions}/-{pr_data.total_deletions}
- 리뷰된 파일: {len(file_reviews)}개

---
*🤖 Generated by Almagest Reviewer*
"""

        return {
            "final_review": fallback_comment,
            "review_decision": "COMMENT",
            "errors": [f"Summary generation failed: {str(e)}"]
        }
