"""
Review Summary Prompt
"""
from app.models import PRData


def create_summary_prompt(
    pr_data: PRData,
    pr_intent: dict,
    risk_assessment: dict,
    file_reviews: list[dict]
) -> str:
    """
    최종 리뷰 요약을 생성하는 프롬프트

    Args:
        pr_data: PR 데이터
        pr_intent: PR 의도 분석 결과
        risk_assessment: 위험도 평가 결과
        file_reviews: 파일별 리뷰 결과 목록

    Returns:
        프롬프트 문자열
    """
    # 이슈 집계
    all_issues = []
    blocking_count = 0
    needs_changes_count = 0
    minor_issues_count = 0
    lgtm_count = 0

    for review in file_reviews:
        status = review.get('status', 'UNKNOWN')
        if status == 'BLOCKING':
            blocking_count += 1
        elif status == 'NEEDS_CHANGES':
            needs_changes_count += 1
        elif status == 'MINOR_ISSUES':
            minor_issues_count += 1
        elif status == 'LGTM':
            lgtm_count += 1

        for issue in review.get('issues', []):
            all_issues.append({
                'file': review['filename'],
                'severity': issue.get('severity', 'unknown'),
                'type': issue.get('type', 'unknown'),
                'message': issue.get('message', ''),
                'suggestion': issue.get('suggestion', '')
            })

    # 심각도별 이슈 분류
    high_issues = [i for i in all_issues if i['severity'] == 'high']
    medium_issues = [i for i in all_issues if i['severity'] == 'medium']
    low_issues = [i for i in all_issues if i['severity'] == 'low']

    # 파일별 리뷰 요약
    file_summaries = []
    for review in file_reviews[:10]:  # 최대 10개만
        file_summaries.append(f"""
**{review['filename']}** ({review.get('status', 'UNKNOWN')})
- 이슈: {len(review.get('issues', []))}개
- 요약: {review.get('summary', 'N/A')}
""")

    return f"""당신은 팀 리드 개발자로서 모든 파일 리뷰를 종합하여 최종 의견을 작성합니다.

## PR 개요
**제목:** {pr_data.title}
**작성자:** @{pr_data.author.login}
**의도:** {pr_intent.get('summary', 'N/A')} ({pr_intent.get('type', 'unknown')})
**위험도:** {risk_assessment.get('level', 'UNKNOWN')} ({risk_assessment.get('score', 0)}/10)

## 변경 통계
- 파일: {pr_data.changed_files_count}개
- 변경량: +{pr_data.total_additions}/-{pr_data.total_deletions} 줄
- 커밋: {pr_data.commits_count}개

## 리뷰 결과 집계
- ✅ LGTM: {lgtm_count}개 파일
- ⚠️ MINOR_ISSUES: {minor_issues_count}개 파일
- 🔧 NEEDS_CHANGES: {needs_changes_count}개 파일
- 🚫 BLOCKING: {blocking_count}개 파일

## 심각도별 이슈
- 🔴 HIGH: {len(high_issues)}개
- 🟡 MEDIUM: {len(medium_issues)}개
- 🟢 LOW: {len(low_issues)}개

## 주요 이슈 목록
{chr(10).join([
    f"- [{i['severity'].upper()}] {i['file']}: {i['message']}"
    for i in (high_issues + medium_issues)[:5]
]) if (high_issues + medium_issues) else "(심각한 이슈 없음)"}

## 파일별 리뷰 요약
{chr(10).join(file_summaries) if file_summaries else "(리뷰 없음)"}

---

위 정보를 바탕으로 **GitHub PR에 게시할 최종 리뷰 코멘트**를 작성해주세요.

다음 형식으로 JSON 응답해주세요:

```json
{{
  "decision": "APPROVE | REQUEST_CHANGES | COMMENT",
  "summary": "전체 평가를 2-3문장으로 요약",
  "comment": "실제 GitHub에 게시될 마크다운 코멘트 (아래 형식 참고)",
  "action_items": [
    "수정이 필요한 항목 1",
    "수정이 필요한 항목 2"
  ]
}}
```

**comment 필드는 다음 마크다운 형식을 따라주세요:**

```markdown
## 🤖 AI 코드 리뷰

### 📋 요약
[전체 평가 요약]

### ✅ 잘된 점
- [긍정적인 부분 1]
- [긍정적인 부분 2]

### ⚠️ 주요 이슈
#### 🔴 High Priority
1. **[파일명]**: [문제 설명]
   - 제안: [해결 방법]

#### 🟡 Medium Priority
1. **[파일명]**: [문제 설명]

### 💡 제안사항
- [개선 제안 1]
- [개선 제안 2]

### 🎯 결론
[최종 판단 및 다음 단계]

---
*🤖 Generated by Almagest Reviewer*
```

**decision 기준:**
- **APPROVE**: 이슈가 없거나 모두 low severity, 머지 가능
- **REQUEST_CHANGES**: high severity 이슈가 있거나 blocking 파일이 있음
- **COMMENT**: medium 이하 이슈만 있지만 의견을 남김

JSON만 응답해주세요."""
